// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProperTea.UserManagement.Infrastructure.Persistence;

#nullable disable

namespace ProperTea.UserManagement.Infrastructure.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20250910055914_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProperTea.UserManagement.Domain.SystemUsers.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("ProperTea.UserManagement.Domain.SystemUsers.SystemUser", b =>
                {
                    b.OwnsOne("ProperTea.Domain.Shared.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("SystemUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("SystemUserId");

                            b1.HasIndex(new[] { "Value" }, "IX_Organization_Name")
                                .IsUnique();

                            b1.ToTable("SystemUsers");

                            b1.WithOwner()
                                .HasForeignKey("SystemUserId");
                        });

                    b.OwnsOne("ProperTea.Domain.Shared.ValueObjects.PersonFullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("SystemUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("SystemUserId");

                            b1.HasIndex(new[] { "Value" }, "IX_Organization_Name")
                                .IsUnique()
                                .HasDatabaseName("IX_Organization_Name1");

                            b1.ToTable("SystemUsers");

                            b1.WithOwner()
                                .HasForeignKey("SystemUserId");
                        });

                    b.OwnsMany("ProperTea.UserManagement.Domain.SystemUsers.OrganizationMembership", "OrganizationMemberships", b1 =>
                        {
                            b1.Property<Guid>("SystemUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("datetime2");

                            b1.Property<int>("OrganizationRole")
                                .HasColumnType("int");

                            b1.HasKey("SystemUserId", "Id");

                            b1.ToTable("OrganizationMembership");

                            b1.WithOwner()
                                .HasForeignKey("SystemUserId");
                        });

                    b.OwnsMany("ProperTea.UserManagement.Domain.SystemUsers.UserIdentity", "UserIdentities", b1 =>
                        {
                            b1.Property<Guid>("SystemUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("SystemUserId", "Id");

                            b1.ToTable("UserIdentity");

                            b1.WithOwner()
                                .HasForeignKey("SystemUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("UserIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
