// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProperTea.SystemOwner.Infrastructure.SystemOwner.Data;

#nullable disable

namespace ProperTea.SystemOwner.Infrastructure.Migrations
{
    [DbContext(typeof(SystemOwnerDbContext))]
    partial class SystemOwnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProperTea.SystemOwner.Domain.SystemOwner.SystemOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_SystemOwner_Name")
                        .IsUnique();

                    b.ToTable("SystemOwners");
                });
#pragma warning restore 612, 618
        }
    }
}
